/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#191b22",
        outline: "#8e909f",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#001550",
        "on-secondary-container": "#003e1c",
        "on-secondary-fixed": "#00210c",
        "surface-dim": "#111319",
        "on-tertiary-fixed": "#2a1700",
        "surface-tint": "#b6c4ff",
        "primary-container": "#6c8cff",
        secondary: "#4de082",
        "on-error": "#690005",
        primary: "#b6c4ff",
        "on-primary-fixed-variant": "#0d3bad",
        error: "#ffb4ab",
        "on-secondary": "#003919",
        "on-tertiary-container": "#412600",
        "on-primary": "#002780",
        "surface-bright": "#373940",
        "tertiary-fixed-dim": "#ffb95f",
        surface: "#111319",
        "surface-container": "#1e1f26",
        "on-surface": "#e2e2eb",
        background: "#111319",
        "inverse-on-surface": "#2e3037",
        "primary-fixed": "#dce1ff",
        "tertiary-container": "#cd8300",
        "surface-variant": "#33343b",
        "error-container": "#93000a",
        "on-surface-variant": "#c4c5d5",
        "secondary-fixed": "#6dfe9c",
        "inverse-surface": "#e2e2eb",
        "tertiary-fixed": "#ffddb8",
        "outline-variant": "#444653",
        "on-secondary-fixed-variant": "#005227",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#472a00",
        "inverse-primary": "#3255c6",
        "surface-container-highest": "#33343b",
        tertiary: "#ffb95f",
        "on-primary-container": "#002376",
        "secondary-fixed-dim": "#4de082",
        "on-background": "#e2e2eb",
        "secondary-container": "#00b55d",
        "surface-container-high": "#282a30",
        "surface-container-lowest": "#0c0e14",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"],
        "metric-num": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "metric-num": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
